name: Default Workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      
      - run: make test
